run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - gosec
    - prealloc

linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: github.com/valeria/GophKeeper
  misspell:
    locale: US
  gosec:
    excludes:
      - G104

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - noctx

